company-library/company-library

- pages/_app.tsx
- pages/_middleware.tsx
- pages/auth/signIn.tsx
> AzureAD B2Cの認証をmiddlewareで実施する

- src/components/layout.tsx
- src/components/navigationBar.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/private.tsx
- tsconfig.json
- tailwind追加のついでに、navigationバーを追加
- 絶対パスでインポートできるように変更
> navigationバーの追加

- .github/workflows/codeql-analysis.yml
コードの性的な脆弱性検査のために、codeQLというサービスを使用しようと思います
https://docs.github.com/ja/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
> CodeQLによるcode scanningの追加

- hasura/migrations/default/1658557984460_alter_table_public_users_add_column_sub/down.sql
- hasura/migrations/default/1658557984460_alter_table_public_users_add_column_sub/up.sql
- hasura/migrations/default/1658573281430_alter_table_public_users_alter_column_image_url/down.sql
- hasura/migrations/default/1658573281430_alter_table_public_users_alter_column_image_url/up.sql
- src/generated/graphql.ts
- src/generated/schema.graphql
- src/libs/graphql-codegen/sdk.ts
- src/pages/api/auth/[...nextauth].ts
- src/repositories/queries.graphql
- DBからユーザー情報の取得
- DBにユーザーが登録されていなければ、インサートする
fix #47
> sessionのcallbackでユーザー情報の取得

- src/components/googleBook.tsx
- src/generated/graphql.client.ts
- src/generated/graphql.ts
- src/repositories/queries.graphql
- test/components/googleBook.test.tsx
本を登録する画面から、登録（本が登録されていない場合）、追加（すでに書籍が登録されている場合）をできるようにしました。
fix #8
> 本を取得するAPIの追加

- src/components/bookDetail.tsx
- src/components/returnButton.tsx
- src/generated/graphql.client.ts
- src/generated/graphql.ts
- src/hooks/useLend.ts
- src/hooks/useReturn.ts
- src/repositories/queries.graphql
- test/components/bookDetail.test.tsx
- test/components/returnButton.test.tsx
- test/hooks/useLend.test.ts
- test/hooks/useReturn.test.ts
> 返却の記録を残せるようにする

- src/components/bookDetail.tsx
- src/components/bookDetails/impressionList.tsx
- src/components/returnButton.tsx
- src/constants.ts
- src/generated/graphql.client.ts
- src/generated/graphql.ts
- src/hooks/useReturn.ts
- src/repositories/queries.graphql
- test/components/bookDetail.test.tsx
- test/components/bookDetails/impressionList.test.tsx
- test/components/returnButton.test.tsx
- test/hooks/useReturn.test.ts
fix #14 
- 返却時に感想を残せるようにした
- 残した感想を確認できるようにデザインに合わせて感想を表示するようにした
> 返却時に感想を残せるようにする

- package.json
- yarn.lock
#86 のプルリクで、議論していたsuperjsonが不要ではないかということについて、確かに削除しても問題なさそうということが分かったので削除します
> superjsonの削除

- src/app/users/[id]/bookList.tsx
- src/app/users/[id]/page.tsx
- src/app/users/userCard.tsx
- src/hooks/server/readingHistories.ts
- src/models/user.ts
- test/__utils__/data/lendingHistory.ts
- test/__utils__/data/user.ts
- test/app/users/id/bookList.test.tsx
- test/app/users/id/page.test.tsx
- test/hooks/server/readingHistories.test.ts
> useCardでreadingHistories関数を使用するように変更

- src/app/navigationBar.tsx
- test/app/navigationBar.test.tsx
fix #145 
どこまで効果があるかわかりませんが、daisyUIのnavbarを使用します
https://daisyui.com/components/navbar/
> プロダクト名をクリックしたときに、TOPページに遷移できるようにする

- src/app/layout.tsx
- src/app/page.tsx
- src/components/bookTile.tsx
> 書籍一覧画面のタイルのサイズをそろえる

- next-env.d.ts
- package.json
- src/app/books/[id]/lendButton.tsx
- src/app/books/[id]/returnButton.tsx
- yarn.lock
fix #153 
daisy uiのカラーテーマがv2からv4(最新)で変更があり、v4のものを反映させるために daisy ui 自体もアップデートしました
> 借りると返却のボタンをdaisyUIの標準のものに変更する

- src/components/userAvatar.tsx
> 書籍詳細画面のアバターのアイコンサイズを揃える

- src/app/users/userCard.tsx
> 利用者一覧画面で全てのユーザーにアバターが表示されるようにする

- src/app/books/[id]/actions.ts
- src/app/books/register/actions.ts
> 不要なFQDN指定を削除

- schema.prisma
データは消えますが `yarn db:push` して、その後 `yarn db:seed` して動作確認しました
> DBのカラム名をスネークケース名に変更

- .env.examle
- package.json
- src/app/books/register/actions.ts
- src/libs/slack/webhook.ts
- test/app/books/register/actions.test.ts
- test/libs/slack/webhook.test.ts
- yarn.lock
> 書籍の新規登録をSlack通知する

- src/app/navigationBar.tsx
- src/components/userAvatar.tsx
- test/app/navigationBar.test.tsx
- test/components/userAvatar.test.tsx
> ヘッダーにログインユーザーアイコンを表示する

- .env.examle
- next.config.js
- package.json
- src/app/books/register/actions.ts
- src/libs/vercel/downloadAndPutImage.ts
- test/app/books/register/actions.test.ts
- test/app/books/register/bookForm.test.tsx
- test/app/books/register/page.test.tsx
- test/app/books/register/searchedBook.test.tsx
- test/libs/vercel/donwloadAndPutImage.test.ts
- yarn.lock
fix #171 
@katakoto291 と相談し、Google Books APIの画像はjpgのみと決め打ちして実装しました
> 書影をvercel blobに保存する

- prisma/seed.ts
- src/app/books/[id]/lendButton.tsx
- test/app/books/id/lendButton.test.tsx
> 借りる時の入力フォームのデザインを改善

- src/app/books/[id]/returnButton.tsx
- test/app/books/id/returnButton.test.tsx
> 返す時の入力フォームのデザインを改善

- src/app/books/[id]/actions.ts
- src/app/books/[id]/lendButton.tsx
- src/app/books/[id]/returnButton.tsx
- test/app/books/id/actions.test.ts
- test/app/books/id/lendButton.test.tsx
- test/app/books/id/returnButton.test.tsx
> 返却処理のバグの修正

- renovate.json
fix #184 
#193 で自動作成されたPR単体でもマージできる余地を残すために、別PRとして作成してみました。
設定内容自体は、 #191 と同様になるようにしているつもりです。
#193 をマージしてからこのPRをマージするか、 このPRをマージするだけにするか相談できればと思います
（ #193 を先にマージすると、そのPRに記載されているアップデート用のPRが作成されてしまうかもしれないと懸念）
（デフォルトだと最大2つまでらしいので問題ないかも）
> Renovate の設定を行う

- .env.example
- README.md
- src/libs/slack/webhook.ts
デプロイするための補足として、アーキテクチャ図も追加しました
> README.mdにデプロイの手順を追加

- next.config.js
- src/app/navigationBarItem.tsx
> typedRoutesをtrueにしてみる

- .github/workflows/buildCheck.yml
- .github/workflows/typeCheck.yml
- src/app/books/[id]/lendButton.tsx
- src/app/books/[id]/returnButton.tsx
- src/app/navigationBarItem.tsx
company-library/company-library は vercel環境にデプロイされないため、ビルドに通らないが、ほかのテストは通って問題無いように見えてしまうことがある
したがって、ビルドのチェックを入れるようにします
また、型チェックをするgithub actionsも追加します
コミットログがおかしくなり、force pushした影響で関連付けがなくなってしまっていますが、最初のコミットでテストが落ちることを確認しています
- https://github.com/company-library/company-library/actions/runs/9447690458
- https://github.com/company-library/company-library/actions/runs/9447690442
> ビルドと型チェックをするgithub actionsを追加

- .github/workflows/reviewdogBiome.yml
以下の内容の改善を加えます
- ラベルを付けるとテストが走るようになる
- 誤りがあった時にpull requestにコメントされる
> biomeのチェックをするgithub actionsの改善

- package.json
- yarn.lock
#172 と #174 により使用しなくなったのでアンインストール
> 使用しなくなったので Headless UI を削除

- .env.example
- src/app/api/cron/overdue/route.ts
- src/libs/slack/webhook.ts
- test/app/api/cron/overdue/route.test.ts
- test/libs/slack/webhook.test.ts
- vercel.json
> 返却期限を超過した書籍を通知する

- .github/workflows/codeql.yml
#374 を見ていて、他のリポジトリからのプルリクエストの場合、フォークしたリポジトリでの設定によってcodeqlが実行されないことがあることがわかりました
workflowとして追加することで、確実に実行されるようにします
githubのcodeqlの設定画面で、デフォルトで作られたymlをcommitしました
フォークしたリポジトリのプルリクエストで、codeqlのワークフローが動作することを確認
> codeql.yml の追加

- src/app/books/[id]/bookDetail.tsx
- src/components/bookTile.tsx
- src/components/userAvatar.tsx
動作確認している時に、Imageコンポーネントが出している警告が気になったので、出ないように修正してみました
> Imageコンポーネントに関する警告を解消

- src/app/books/[id]/actions.ts
- src/app/books/[id]/editImpressionButton.tsx
- src/app/books/[id]/impressionList.tsx
- src/app/books/[id]/lendButton.tsx
- src/app/books/[id]/page.tsx
- src/app/books/[id]/returnButton.tsx
- src/constants.ts
- src/libs/luxon/utils.ts
- test/app/books/id/actions.test.ts
- test/app/books/id/editImpressionButton.test.tsx
- test/app/books/id/impressionList.test.tsx
- test/app/books/id/lendButton.test.tsx
- test/app/books/id/page.test.tsx
- test/app/books/id/returnButton.test.tsx
> 感想の編集ができるようにする

- package.json
- src/app/books/[id]/actions.ts
- src/app/books/[id]/addImpressionButton.tsx
- src/app/books/[id]/bookDetail.tsx
- test/app/books/id/actions.test.ts
- test/app/books/id/addImpressionButton.test.tsx
- test/app/books/id/bookDetail.test.tsx
- yarn.lock
Fix #268 
- Sever Actions と useActionState を使ってみたかったので、それを用いています
- 入力内容の検証にZodを使うようにしてみています
> 書籍を借りずに感想が残せるようにする

- src/app/api/books/search/route.ts
- test/app/api/books/search/route.test.ts
> 表示順を作成日の降順に変更

- src/app/books/[id]/impressionList.test.tsx
- src/app/books/[id]/impressionList.tsx
- src/app/books/[id]/lendingList.test.tsx
- src/app/books/[id]/lendingList.tsx
- src/app/books/[id]/returnList.test.tsx
- src/app/books/[id]/returnList.tsx
- src/components/userAvatar.test.tsx
- src/components/userAvatar.tsx
> 書籍の詳細ページにおいて、ユーザーアイコンをリンクにする

- .github/workflows/buildCheck.yml
- .github/workflows/typeCheck.yml
- .github/workflows/unitTest.yml
- typeCheck でエラーになっていた場合があったため、修正できればと思います
- エラーの原因は、Prismaクライアントの型が無いことのようだったので、明示的に生成する処理を GitHub Actions に追加してみました
- ただ、別のタイミングではエラーにならなくなっていたので、対応しなくてもいいかもしれないです
- typeCheck がエラーになっていないこと
- なし
- なし
> typeCheck のエラーの解消

- prisma/seed.ts
- seed 実行時にシーケンスもリセットされた方がいいように感じたので対応してみました
- ただ、そのために生のSQLを書く必要がありそうなので、微妙そうでしたら、Approve頂かなくて大丈夫です〜
- 特になし
- なし
> seed実行時にシーケンスもリセットする
