company-library/company-library

- src/components/navigationBar.tsx
- test/components/navigationBar.test.tsx
fix #80 
- 未返却一覧をクリックすると自身のプロフィール画面に遷移するよう変更
> 未返却一覧をクリックすると自身のプロフィール画面に遷移するよう変更

- test/components/user.test.tsx
- Userコンポーネントのテスト実行時にwarningが出ていたため、warningが出ないよう修正しました
- 原因：Userコンポーネント内で使用しているBookListコンポーネント内部でGETクエリを実行しており、そのGETクエリがモックされていなかったこと
- 対処法：BookListコンポーネントをモックする
> テスト実行時に発生していたwarningを解消する

- schema.prisma
prisma v5で指定不要になったということなので、削除したいと思います。
参考
https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#jsonprotocol-out-of-preview
> jsonProtocolの指定の削除

- src/app/api/auth/[...nextauth]/route.ts
- src/app/layout.tsx
- src/models/user.ts
- sessionからprismaで取得したユーザーIDが取得できるように、ユーザーがDBに存在するかの判定をprismaで行うようにしました
- App Routerにしました
- App Routerにしたときに、`export default NextAuth({...})`だと、App RouterのAPIルートの書き方と合わないため、下記を参考に修正しました
- https://qiita.com/kage1020/items/8224efd0f3557256c541#%E5%AE%9F%E8%A3%85
> auth apiのApp Router化 

- .github/DISCUSSION_TEMPLATE/architecture-decision-record.yml
DiscussionsでADRを保持していくことにしたものの、テンプレートがないためにフォーマットがバラバラになりそうだった。
@katakoto291 さんより、 テンプレートの作成のやり方を教えていただいたので、それを反映します。
https://tech.excite.co.jp/entry/2023/07/24/100404
> ADRのDiscussionテンプレートの追加

- src/app/navigationBar.tsx
- test/app/navigationBar.test.tsx
fix #147 
ユーザー名を表示します
ロゴの表示については #150 の対応が完了したのちに、対応することを想定し、 #156 を追加しました
また、 #156 をfirst releaseでリリースするかはわからないので、NoStatusのバックログに追加しました
> ヘッダーにログインユーザー情報を表示する

- next.config.js
- src/app/users/userCard.tsx
- src/components/userAvatar.tsx
- src/libs/gravatar/getAvatarUrl.ts
- test/app/books/id/impressionList.test.tsx
- test/app/books/id/lendingList.test.tsx
- test/app/books/id/returnList.test.tsx
- test/app/users/page.test.tsx
- test/app/users/userCard.test.tsx
- test/components/userAvatar.test.tsx
- test/libs/gravatar/getAvatar.test.ts
[Gravatarのドキュメント](https://docs.gravatar.com/)を参考に実装
gravatarから取得できなかった場合は、ユーザー名の戦先頭文字のアイコンを表示するようにしています。
> ユーザーアバターを gravatar から取得する

- src/app/layout.tsx
画面によってスクロールバーが表示されて、それによって画面が横にずれます
ビューポート（vw）でスクロールバーの幅込みで、幅指定を行い、画面ずれを防ぎます
fix #143
> 画面によって横にずれる問題に対応

- .github/dependabot.yml
#184 
- `groups` を設定するために `dependabot.yml` の追加
- `next` 系をまとめる設定を追加
- `prisma` 系をまとめる設定を追加
- マイナーバージョンとパッチバージョンのアップデートはまとめられるようにする
- 確認頻度や時間について決めたい
> next 系パッケージのアップデートPRがまとめられるようにする

- renovate.json
- `next` と `eslint-config-next` のグループ化よりも マイナーバージョンとパッチバージョンのグループ化が優先されてしまっているため、修正します
- [ドキュメント](https://docs.renovatebot.com/configuration-options/#packagerules)に以下のようにあったので、記載順を逆にしました
> packageRulesの順番は、最も重要でないルールを一番上に、最も重要なルールを一番下にします。こうすることで、必要に応じて重要なルールがそれ以前のルールの設定を上書きします。
> renovate のグループ化の優先順位の修正

- README.md
zennの記事を書いているときにGoogle Books APIの記載を忘れていることに気づいたので追記します
> アーキテクチャ図にGoogle Books APIの記載を追加

- .github/dependabot.yml
This reverts commit 39b823163d4a3fb7abd895e8053ac2b58bd09d64.
> renovate が yarn v4 でinstall してくれないので、 dependabotのVersion Update の無効化をRevert

- .github/dependabot.yml
renovate のように、　Docker 関連のバージョンアップデートも行ってもらいたいため、追加します
> `docker-compose.yml` についてもチェックされるようにdependabotの対象に追加

- test/app/books/id/lendButton.test.tsx
- yarn.lock
#245  がエラーになっていたので、そのエラーを解消します
- `yarn install` の実行 1b2f6d66a37089736f2d54f0ab8cf002382224ab
- テストコードで型エラーが発生してたため修正 1372afa231e75d8c3ff193491e92a1c7fc0b79a5
- test 実行時に以下の警告が出ていますが、一旦テストは通っているのと `@testing-library/react` のアップデートが必要そうに見えたので、別途対応できればと考えています
```
Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.
```
> マイナーバージョンとパッチバージョンアップデートエラーの解消

- vercel.json
cron式が誤っていたためVercelでデプロイできなくなってしまっていたので修正します
以下のサイトで有効なcron式になっているか確認しました
https://vercel.com/docs/cron-jobs#validate-cron-expressions
> cron式が誤っていたため修正

- renovate.json
renovateがlockファイルを上げるとyarn v1になって、そのあとの作業が煩雑になるので、ロックファイルの更新はrenovateを使用せず、各自のローカルで実行するようにしたい
renovateの設定を変更し、lockファイルを更新しない設定とした
> renovateにlockファイルの更新をさせない

- .github/workflows/buildCheck.yml
- .github/workflows/reviewdogBiome.yml
- .github/workflows/typeCheck.yml
- .github/workflows/unitTest.yml
Potential fix for [https://github.com/company-library/company-library/security/code-scanning/59](https://github.com/company-library/company-library/security/code-scanning/59)
To fix the issue, we will add a `permissions` block at the workflow level (applies to all jobs) with the least privileges required. Since the workflow only checks out the repository and runs tests, it only needs `contents: read` permission. This ensures that the `GITHUB_TOKEN` used in the workflow has minimal access, reducing the risk of unintended actions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 59: Workflow does not contain permissions

- .github/workflows/buildCheck.yml
- .github/workflows/dependency-review.yml
- .github/workflows/reviewdogBiome.yml
- .github/workflows/typeCheck.yml
- .github/workflows/unitTest.yml
Third partyのgithub actionsに関しては、コミットhashで固定したほうがいいとのことで対応
https://github.com/company-library/company-library/security/code-scanning/63
[pinact](https://github.com/suzuki-shunsuke/pinact)を使用して、一括で置換しました
> github actionsのバージョン指定をhashに変更

- src/app/users/userCard.tsx
- 利用者一覧画面の冊数が、ダークモード時に背景色と同化して見えなくなってしまっていたため修正します
- 文字色を明示的に指定することでダークモード時でも適した色になるようにしました
修正後のライトモードも確認
> ダークモードに対応した文字色に修正

- src/app/books/register/searchedBook.tsx
- src/constants.ts
- test/app/books/register/searchedBook.test.tsx
Fix #309 
Googleの方で見つからなかった時だけでなく、常にopenBDからも取得して、Googleの方でなかったらopenBDのものを使うようにしてみました
> Google Books Api で書籍が見つからなかった時にopenBDの書籍をを用いるよう変更

- src/middleware.ts
- vercel.json
Cron Job用のAPI RouteがNextAuthによって認証を必要としていたため実行されない状態だったので、実行されるように修正します
また、実行スケジュールも日本時間の水曜日午前8時頃に実行されるようになっていなかったため修正しました
> Cron Jobが実行されるようにする

- src/app/books/[id]/editImpressionButton.tsx
- src/app/books/[id]/impressionList.tsx
- test/app/books/id/editImpressionButton.test.tsx
感想の長さによって、編集ボタンの表示位置が変わったり、表示が崩れたりしたので修正します
> 感想が横幅一杯になるように感想リストのデザイン修正

- src/app/api/books/search/route.test.ts
- src/app/api/books/search/route.ts
- src/app/bookList.test.tsx
- src/app/bookList.tsx
- src/app/books/register/addBookDiv.tsx
- src/app/books/register/registerBookDiv.tsx
- src/models/location.ts
TOPページでの書籍の絞り込み項目に保管場所を追加します
- 「全ての保管場所」を選択したときに、全ての保管場所の書籍が表示されること
- 保管場所を選択したときに、選択した保管場所の書籍が表示されること
- 書籍のタイトルでも絞り込めること
- 8/3
fix #401
> 保管場所で絞り込めるようにする

- next.config.mjs
- Next.js 15.5 で [`typedRoutes` が安定版](https://nextjs.org/blog/next-15-5#typed-routes-stable)になり `build` 時に 以下の警告が出ていたため対応したいです
```
⚠ `experimental.typedRoutes` has been moved to `typedRoutes`. Please update your next.config.mjs file accordingly.
```
- なし
- なし
> next.js 15.5 用に next.config.js を更新

- .gitignore
- biome.json
- prisma/schema.prisma
- prisma/seed.ts
- src/libs/prisma/client.ts
- src/models/book.ts
- src/models/lendingHistory.ts
- src/models/returnHistory.ts
- test/__utils__/libs/prisma/singleton.ts
- Prisma Client の generator が Prisma v7 から ESM対応にしたものになる予定であるため #443 と同様に先行して対応できたらと思います
- https://www.prisma.io/blog/why-prisma-orm-generates-code-into-node-modules-and-why-it-ll-change
- https://www.prisma.io/docs/orm/prisma-schema/overview/generators#prisma-client-preview
- とくになし
- #421
> Prisma Client の generator を新しいものに変更
